// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Todo interface {
	IsTodo()
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Test struct {
	ID    string   `json:"id"`
	Text  string   `json:"text"`
	Done  bool     `json:"done"`
	User  *User    `json:"user"`
	Ref   string   `json:"ref"`
	Index *int     `json:"index"`
	Price *float64 `json:"price"`
}

func (Test) IsTodo() {}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
